# Base configs
baseurl: "https://mkodoherty.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "MKO Art"
subtitle: ""
author: "M. K. O'Doherty"
header:
 title: "Art"
 subtitle: "by Megan O'Doherty"
footer:
 name: ""
 bio: ""
 github: "<a href=\"https://github.com/ramswaroop/photography\"></a>"
web_design: ""
social_urls:
 facebook: ""
 twitter: ""
 instagram: ""
 dribbble: ""
 linkedin: ""
 github: ""
